# Site settings
title: 川川的博客
SEOTitle: 川川的博客 | LYF Blog
header-img: img/post-bg-desk.jpg
email: liyfwork@qq.com
description: "技术分享博客"
keyword: "LYF, LYF Blog, 川川的博客, liyff, 川川, iOS, Apple, iPhone"
url: "http://liyff.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Liyff/liyff.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Do it, then perfect it."
sidebar-avatar: https://github.com/Liyff/liyff.github.io/blob/master/img/avatar-by%20.jpg?raw=true      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     qiubaiying
github_username:    qiubaiying
facebook_username:  baiying.qiu.7
jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: liyf

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Iv23liYmziwYRb0MLgB4                            #生成的clientID
  clientSecret: 6cd9a9feb67c5c2ef4eee103bb607c990a51229e    #生成的clientSecret
  repo: liyff.github.io    #仓库名称
  owner: liyff    #github用户名
  admin: liyff
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: f55af03f7f6377dc338873202cbe06e5

# Google Analytics
ga_track_id: 'GT-WBZPSJST'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
